#!/usr/bin/env node

/* jshint esversion: 6 */

const fs = require('fs-extra');
const path = require('path');
const spawn = require('child_process').spawnSync;
const copy = require('recursive-copy');
const rimraf = require('rimraf');
const which = require('which');
const program = require('commander');

const { recursiveCopyFilter } = require('./scripts/distContents');
const { resolveVersionAndRelease } = require('./scripts/packageVersion');
const pkginfo = require('./package.json');
const plugininfo = require('./src/plugin.json');

try {
  which.sync('dpkg-buildpackage');
} catch (err) {
  console.log('dpkg-buildpackage executable not found');
  process.exit(1);
}

// The previous `if (version.indexOf('-SNAPSHOT'))` was truthy for -1 too, so every
// build was released as 0 whether or not it was a snapshot.
const { version, release: defaultRelease } = resolveVersionAndRelease(pkginfo.version);

program
  .version(pkginfo.version)
  .option('-r --release <release>', 'Specify release number of package', defaultRelease)
  .parse(process.argv);

const release = program.opts().release;

pkginfo.version = version;
pkginfo.release = release;


const date = new Date().toUTCString().replace(/ [^ ]+$/, ' +0000');
const changelog = `${pkginfo.name} (${version}-${release}) unstable; urgency=low

  * Autogenerated package.

 -- Benjamin Reed <ranger@opennms.org>  ${date}
`;

const pkgid   = plugininfo.id;
const workdir = path.join(process.cwd(), 'artifacts', pkgid);
const distdir = path.join(process.cwd(), 'dist');

rimraf.sync(workdir);
fs.mkdirsSync(workdir);
return copy(distdir, workdir, {
  dot: true,
  junk: false,
  filter: recursiveCopyFilter([
    '!**/*.changes',
    '!**/*.deb',
    '!**/*.dsc',
    '!**/*.tar.gz',
  ])
}).then((results) => {
  console.log(results.length + ' files copied to ' + workdir);

  const debian = path.join(workdir, 'debian');
  fs.mkdirsSync(debian);

  return copy(path.join(process.cwd(), 'src', 'debian'), debian).then((_copyResults) => {
    console.log('debian/ directory copied');

    console.log('* writing changelog');
    const fh = fs.openSync(path.join(debian, 'changelog'), 'w+');
    fs.writeSync(fh, changelog);
    fs.closeSync(fh);

    console.log('* running dpkg-buildpackage');
    const ret = spawn('dpkg-buildpackage', [], {
      cwd: workdir,
      stdio: ['inherit', 'inherit', 'inherit'],
    });
    if (ret.error) {
      console.log('dpkg-buildpackage failed: ' + ret.error.message);
      process.exit(1);
    }

    // spawnSync reports a non-zero exit only in `status`, never in `error`.
    if (ret.status !== 0) {
      console.log('dpkg-buildpackage exited with status ' + ret.status);
      process.exit(1);
    }

    rimraf.sync(workdir);

    process.exit(0);
  });
}).catch((error) => {
  console.log('Copy failed: ' + error);
  process.exit(1);
});
