
= Requirements
:description: Learn the prerequisites to install the {product-name}, which lets you create flexible dashboards to visualize and interact with data stored by OpenNMS.

This section describes the requirements to install the {product-name}.

== Runtime requirements

For runtime operations, you need to install and set up either https://www.opennms.com/horizon/[OpenNMS Horizon 33+] or https://www.opennms.com/[Meridian 2024+].
You also need a http://docs.grafana.org/installation[Grafana instance] (version {grafana-version-required} or newer).

NOTE: We have tested the plugin with Grafana version {grafana-version-tested}.
The plugin declares a minimum of Grafana {grafana-version-required}, and Grafana does not load it on earlier versions.
We recommend that you use matching versions of the plugin and Grafana (for example, {product-name} 12.x and Grafana 12.x).

The OpenNMS Grafana Dashboard Report feature requires the https://grafana.com/grafana/plugins/grafana-image-renderer/[Grafana Image Renderer plugin] to be installed.

== Build requirements

To build the plugin, you must have https://nodejs.org/en/download[Node.js] installed (version {node-js-build-version} or newer).

NOTE: This is required only if you are xref:source.adoc[installing the plugin from source].
