'use strict';

// Generates the debian/ metadata that has to agree with package.json: the changelog
// and control. Debian expects the changelog trailer and the control Maintainer to be
// the same identity, so both come from one value here.

const fs = require('fs');
const path = require('path');
const mustache = require('mustache');

const PROJECT_DIR = path.resolve(__dirname, '..', '..');
const CONTROL_TEMPLATE = path.join('src', 'debian', 'control.mustache');

function renderControl({ pkgInfo, maintainer, projectDir = PROJECT_DIR }) {
  const templatePath = path.resolve(projectDir, CONTROL_TEMPLATE);

  if (!fs.existsSync(templatePath)) {
    throw new Error('makedeb: control template not found: ' + templatePath);
  }

  return mustache.render(fs.readFileSync(templatePath, 'utf-8'), {
    name: pkgInfo.name,
    maintainer
  });
}

// dpkg wants RFC822: "Wed, 02 Sep 2026 21:00:00 +0000".
function formatChangelogDate(date) {
  return date.toUTCString().replace(/ [^ ]+$/, ' +0000');
}

function renderChangelog({ pkgInfo, version, release, maintainer, date = new Date() }) {
  return `${pkgInfo.name} (${version}-${release}) unstable; urgency=low

  * Autogenerated package.

 -- ${maintainer}  ${formatChangelogDate(date)}
`;
}

module.exports = { renderControl, renderChangelog, formatChangelogDate };
