'use strict';

// Generates the debian/ metadata that has to agree with package.json: the changelog
// and control. Debian expects the changelog trailer and the control Maintainer to be
// the same identity, so both come from one value here.

const fs = require('fs');
const path = require('path');
const mustache = require('mustache');

const { DEBIAN_DIR } = require('../paths');

const CONTROL_TEMPLATE = 'control.mustache';

// package.json's spec.requires is written RPM-style ("grafana >= 12.0.0"); dpkg wants
// "grafana (>= 12.0.0)". Sharing the list keeps the deb and the rpm from disagreeing
// about which Grafana the plugin needs.
const DEBIAN_OPERATORS = { '>=': '>=', '<=': '<=', '=': '=', '>': '>>', '<': '<<' };

function toDebianDepends(requires) {
  return (requires || [])
    .map((requirement) => {
      const match = /^\s*(\S+?)\s*(>=|<=|>|<|=)\s*(\S+)\s*$/.exec(requirement);

      if (!match) {
        return requirement.trim();
      }

      const [, name, operator, version] = match;

      return name + ' (' + DEBIAN_OPERATORS[operator] + ' ' + version + ')';
    })
    .join(', ');
}

// debianDir is a parameter so the template can be pointed elsewhere in a test; the
// default is the directory the template actually ships in, so nothing has to restate
// where scripts/deb/debian is relative to anything else.
function renderControl({ pkgInfo, maintainer, debianDir = DEBIAN_DIR }) {
  const templatePath = path.join(debianDir, CONTROL_TEMPLATE);

  if (!fs.existsSync(templatePath)) {
    throw new Error('make-deb: control template not found: ' + templatePath);
  }

  return mustache.render(fs.readFileSync(templatePath, 'utf-8'), {
    name: pkgInfo.name,
    description: pkgInfo.description,
    maintainer,
    depends: toDebianDepends((pkgInfo.spec || {}).requires)
  });
}

// dpkg wants RFC822: "Wed, 02 Sep 2026 21:00:00 +0000".
function formatChangelogDate(date) {
  return date.toUTCString().replace(/ [^ ]+$/, ' +0000');
}

function renderChangelog({ pkgInfo, version, release, maintainer, date = new Date() }) {
  return `${pkgInfo.name} (${version}-${release}) unstable; urgency=low

  * Autogenerated package.

 -- ${maintainer}  ${formatChangelogDate(date)}
`;
}

module.exports = { renderControl, renderChangelog, toDebianDepends, formatChangelogDate };
